// Generated by scripts/index-works.mjs — run `npm run index` after changing
// public/works. Edit the filenames, not this file.

export type Work = {
  slug: string;
  title: string;
  year: string;
  src: string;
  kind: "image" | "video";
  /** intrinsic pixel size — reserves the layout box and drives scroll measurement */
  width: number;
  height: number;
  alt: string;
};

export const WORKS: Work[] = [
  {
    slug: "warps01-02",
    title: "Warps 01–02",
    year: "2024",
    src: "/works/Warps01–02-2024.JPG",
    kind: "image",
    width: 5616,
    height: 3744,
    alt: "Warps 01–02",
  },
  {
    slug: "warps03-04",
    title: "Warps 03–04",
    year: "2024",
    src: "/works/Warps03–04-2024.JPG",
    kind: "image",
    width: 5616,
    height: 3744,
    alt: "Warps 03–04",
  },
  {
    slug: "desire-path3",
    title: "Desire Path 3",
    year: "2024",
    src: "/works/DesirePath3-2024.jpg",
    kind: "image",
    width: 2249,
    height: 1800,
    alt: "Desire Path 3",
  },
  {
    slug: "cellular-autonomies",
    title: "Cellular Autonomies",
    year: "2025",
    src: "/works/CellularAutonomies-2025.mp4",
    kind: "video",
    width: 1920,
    height: 1080,
    alt: "Cellular Autonomies",
  },
  {
    slug: "lenticular-study",
    title: "Lenticular Study",
    year: "2024",
    src: "/works/LenticularStudy-2024.jpg",
    kind: "image",
    width: 1244,
    height: 829,
    alt: "Lenticular Study",
  },
  {
    slug: "cellular-autonomies-2",
    title: "Cellular Autonomies",
    year: "2025",
    src: "/works/cellularAutonomies-2025.JPG",
    kind: "image",
    width: 4032,
    height: 3024,
    alt: "Cellular Autonomies",
  },
  {
    slug: "dywaniki4",
    title: "Dywaniki 4",
    year: "2024",
    src: "/works/Dywaniki4-2024.png",
    kind: "image",
    width: 1600,
    height: 1067,
    alt: "Dywaniki 4",
  },
  {
    slug: "darkroom-identity",
    title: "Darkroom Identity",
    year: "2026",
    src: "/works/DarkroomIdentity-2026.mp4",
    kind: "video",
    width: 932,
    height: 818,
    alt: "Darkroom Identity",
  },
  {
    slug: "dywaniki1-2",
    title: "Dywaniki 1–2",
    year: "2024",
    src: "/works/Dywaniki1–2-2024.png",
    kind: "image",
    width: 1600,
    height: 1067,
    alt: "Dywaniki 1–2",
  },
  {
    slug: "osci",
    title: "OSCI",
    year: "2025",
    src: "/works/OSCI-2025.png",
    kind: "image",
    width: 1644,
    height: 1097,
    alt: "OSCI",
  },
  {
    slug: "instrument",
    title: "Instrument",
    year: "2025",
    src: "/works/Instrument-2025.png",
    kind: "image",
    width: 1708,
    height: 1127,
    alt: "Instrument",
  },
];
