/**
 * Rebuilds data/works.ts from whatever is sitting in public/works.
 *
 *   npm run index
 *
 * Naming convention — the filename IS the metadata:
 *
 *   TitleInCamelCase-YEAR.ext        DesirePath3-2024.jpg  → "Desire Path 3", 2024
 *
 * The LAST hyphen-minus separates the year, so en dashes inside a title survive
 * (Warps01–02-2024.JPG → "Warps 01–02", 2024). Acronyms are left alone
 * (OSCI-2025.png → "OSCI").
 *
 * Order is shuffled — deliberately not chronological — but seeded, so it is
 * stable until you ask for a different one:
 *
 *   npm run index -- --seed 7
 */

import { execFileSync } from "node:child_process";
import { readdirSync, writeFileSync } from "node:fs";
import { join, extname, basename } from "node:path";

const WORKS_DIR = "public/works";
const OUT = "data/works.ts";

const IMAGE = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif", ".gif"]);
const VIDEO = new Set([".mp4", ".webm", ".mov"]);

/** camelCase / PascalCase → spaced words, leaving acronyms intact */
const titleFromSlug = (slug) =>
  slug
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .replace(/([A-Za-z])(\d)/g, "$1 $2")
    .replace(/^./, (c) => c.toUpperCase())
    .trim();

const kebab = (s) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const probe = (file) => {
  const out = execFileSync(
    "ffprobe",
    ["-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height", "-of", "csv=p=0", file],
    { encoding: "utf8" },
  );
  const [width, height] = out.trim().split(",").map(Number);
  if (!width || !height) throw new Error(`could not read dimensions from ${file}`);
  return { width, height };
};

const files = readdirSync(WORKS_DIR)
  .filter((f) => !f.startsWith("."))
  .filter((f) => IMAGE.has(extname(f).toLowerCase()) || VIDEO.has(extname(f).toLowerCase()));

if (!files.length) {
  console.error(`No media found in ${WORKS_DIR}.`);
  process.exit(1);
}

const seen = new Set();
const works = files.map((file) => {
  const ext = extname(file).toLowerCase();
  const stem = basename(file, extname(file));

  /* split on the last hyphen-minus: everything before it is the title */
  const cut = stem.lastIndexOf("-");
  const rawTitle = cut === -1 ? stem : stem.slice(0, cut);
  const year = cut === -1 ? "" : stem.slice(cut + 1);

  if (!/^\d{4}$/.test(year)) {
    console.warn(`  ! ${file} — no trailing -YEAR, year left blank`);
  }

  let slug = kebab(rawTitle) || kebab(stem);
  while (seen.has(slug)) slug += "-2";
  seen.add(slug);

  const title = titleFromSlug(rawTitle);
  return {
    slug,
    title,
    year: /^\d{4}$/.test(year) ? year : "",
    src: `/works/${file}`,
    kind: VIDEO.has(ext) ? "video" : "image",
    ...probe(join(WORKS_DIR, file)),
    alt: title,
  };
});

/*
  Shuffle, then push apart any two neighbours sharing a title (a still and a
  video of the same piece read as a stall at the centre line otherwise).
*/
const seedArg = process.argv.indexOf("--seed");
const seed = seedArg === -1 ? 20260810 : Number(process.argv[seedArg + 1]);

const random = (() => {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
})();

works.sort((a, b) => a.src.localeCompare(b.src)); // stable base for the seed
for (let i = works.length - 1; i > 0; i--) {
  const j = Math.floor(random() * (i + 1));
  [works[i], works[j]] = [works[j], works[i]];
}

for (let i = 1; i < works.length; i++) {
  if (works[i].title !== works[i - 1].title) continue;
  const swap = works.findIndex(
    (w, k) =>
      k > i &&
      w.title !== works[i - 1].title &&
      w.title !== works[i].title &&
      (k + 1 >= works.length || works[k + 1].title !== works[i].title),
  );
  if (swap !== -1) [works[i], works[swap]] = [works[swap], works[i]];
}

const body = works
  .map(
    (w) => `  {
    slug: ${JSON.stringify(w.slug)},
    title: ${JSON.stringify(w.title)},
    year: ${JSON.stringify(w.year)},
    src: ${JSON.stringify(w.src)},
    kind: ${JSON.stringify(w.kind)},
    width: ${w.width},
    height: ${w.height},
    alt: ${JSON.stringify(w.alt)},
  },`,
  )
  .join("\n");

writeFileSync(
  OUT,
  `// Generated by scripts/index-works.mjs — run \`npm run index\` after changing
// public/works. Edit the filenames, not this file.

export type Work = {
  slug: string;
  title: string;
  year: string;
  src: string;
  kind: "image" | "video";
  /** intrinsic pixel size — reserves the layout box and drives scroll measurement */
  width: number;
  height: number;
  alt: string;
};

export const WORKS: Work[] = [
${body}
];
`,
);

console.log(`Indexed ${works.length} works → ${OUT}`);
for (const w of works) console.log(`  ${w.year}  ${w.title}${w.kind === "video" ? "  (video)" : ""}`);
